### ISSUE TITLE
Parameterize Hard Coded Host pool Attribuites

### ISSUE THREAD

**Issue by ASHR4** [Azure/terraform-azurerm-avm-res-desktopvirtualization-hostpool#14]
Hi @jensheerin,

I was just wondering if I could help contribute to this module by parameterizing some of the hard coded values within the `azurerm_virtual_desktop_host_pool` resource, unless this was left hard coded for a reason?

For example, allowing users to configure `custom_rdp_properties` or even the `load_balancer_type`

Rhys

**Comment by jensheerin** [comment]
Thank you @ASHR4! I have code in progress for an update that will address some of those. I will welcome you contribution after that update.
