### ISSUE TITLE
[AVM Module Issue]: hostpool registration token not in output

### ISSUE THREAD

**Issue by mathiasjespers** [Azure/terraform-azurerm-avm-res-desktopvirtualization-hostpool#30]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### (Optional) Module Version

0.1.4

### Description

Only the azurerm_virtual_desktop_host_pool.this resource is outputed. This makes it impossible to retrieve the much needed registration token info  to register vms to the host pool. I believe adding the azurerm_virtual_desktop_host_pool_registration_info.registrationinfo.token to the output would be beneficial.

Proposed additition in outputs.tf:
```
output "registration_token"  { 
  value = azurerm_virtual_desktop_host_pool_registration_info.registrationinfo.token 
  sensitive = true 
}
```

**Comment by jgenicot** [comment]
I am experiencing the same issue with the AVM module where the hostpool registration token isn't included in the output. The absence of this token complicates the process of registering VMs to the host pool, which is a critical step for us.

**Comment by matt-FFFFFF** [comment]
Hi @jensheerin is it possible to get this output added?
