### ISSUE TITLE
[AVM Question/Feedback]: Hard-coded expiry time of host pool registration token

### ISSUE THREAD

**Issue by lineardraft** [Azure/terraform-azurerm-avm-res-desktopvirtualization-hostpool#46]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

Hello,
Just wanted to check why is the **expiration_date** for **azurerm_virtual_desktop_host_pool_registration_info** hardcoded to **48h**? As far as I know the maximum lifetime of the registration token is ~ 30 days.
The question is, any specific reason why the value is not user customizable? Thanks a lot.

LINK: [https://github.com/Azure/terraform-azurerm-avm-res-desktopvirtualization-hostpool/blob/2e66e67845b1698531aeef683ed7dc2e60f0a1c5/main.tf#L52C3-L52C48](url)

**Comment by jensheerin** [comment]
@lineardraft Thank you for the question! There is no specific reason, you are correct "The expiration period must be a valid duration less than or equal to 30 days."
