### ISSUE TITLE
[AVM Module Issue]: Character Length - Host Pool Name

### ISSUE THREAD

**Issue by Arhughes14** [Azure/terraform-azurerm-avm-res-desktopvirtualization-hostpool#62]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Description

Remove this validation check against this variable:
<img width="506" alt="image" src="https://github.com/user-attachments/assets/08c8c974-bd53-4c06-84b9-69f7515cd403">

The max character limit for host pools is 64 - https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules#microsoftdesktopvirtualization

**Comment by jensheerin** [comment]
@Arhughes14 , thank you for raising the issue. PR #63 resolves the issue.

**Comment by birdnathan** [comment]
@jensheerin - looks like a new version was generated but this hasnt made it to the terraform registry. Looks like an issue witht he version number, can you double check it?
![image](https://github.com/user-attachments/assets/d1b72497-6b75-4c86-b1aa-b356b2ec7991)

**Comment by jensheerin** [comment]
Hi @birdnathan - thank you for bringing up the issue. There was a faulty tag with a typo. It was removed and that resolved the issue. The registry looks updated now. Thank you again!
